// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Blockchains struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type EventFields struct {
	ID        int64     `json:"id"`
	EventID   int64     `json:"event_id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Value     string    `json:"value"`
	Recorder  string    `json:"recorder"`
	CreatedAt time.Time `json:"created_at"`
}

type Events struct {
	ID           int64  `json:"id"`
	BlockchainID int64  `json:"blockchain_id"`
	BlockNumber  int64  `json:"block_number"`
	EventName    string `json:"event_name"`
}

type Users struct {
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
